### ISSUE TITLE
Need to add  BULK COLLECT, FORALL , CURSOR   

### ISSUE THREAD

**Issue by Richabh24** [societe-generale/code2pg#14]
BULK COLLECT =>\bBULK\s*\COLLECT\b
 FORALL  => \bFORALL\b

CURSOR   => \CURSOR\b

### Steps to reproduce the behavior
- code2pg version: `X.Y.Z`
- code2pg parameters: `./code2pg --param1 val1 --param2 val2`
- System: Linux distribution, Perl version

**Comment by e7e6** [comment]
Closed with commit 0dfd4f71c7a5dfe597b114bf9355f72c58e69a2f. All keywords have been added as difficulty level 3.
Thanks for raising the issue, even it was rather sparse :-)
