### ISSUE TITLE
4 "Experimental keys on scalar is now forbidden" error messages at compile time

### ISSUE THREAD

**Issue by beaud76** [societe-generale/code2pg#17]
### Steps to reproduce the behavior
- code2pg version: `0.12.1`
./code2pg --version
Experimental keys on scalar is now forbidden at ./code2pg line 2508.
Type of arg 1 to keys must be hash or array (not hash element) at ./code2pg line 2508, near "})"
Experimental keys on scalar is now forbidden at ./code2pg line 2509.
Type of arg 1 to keys must be hash or array (not hash element) at ./code2pg line 2509, near "})"
Experimental keys on scalar is now forbidden at ./code2pg line 2510.
Type of arg 1 to keys must be hash or array (not hash element) at ./code2pg line 2510, near "})"
Experimental keys on scalar is now forbidden at ./code2pg line 2511.
Type of arg 1 to keys must be hash or array (not hash element) at ./code2pg line 2511, near "})"
Execution of ./code2pg aborted due to compilation errors.
- System: Linux distribution Ubuntu 18.10, Perl version : 
This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-linux-gnu-thread-multi
(with 63 registered patches, see perl -V for more detail)
Found on Internet : 
"The used perl feature was added in Perl 5.14 but removed in 5.23. Experimental %s on scalar is now forbidden (F) An experimental feature added in Perl 5.14 allowed each, keys, push, pop, shift, splice, unshift, and values to be called with a scalar argument. This experiment is considered unsuccessful, and has been removed. The postderef feature may meet your needs better."

**Comment by e7e6** [comment]
Thanks for raising the issue Philippe. I will have a look next week.

**Comment by e7e6** [comment]
Hi Philippe,

code2pg has been updated (commit b54fc8166dc1f985a3b5cbdd2edf10a5e827280a) and the new release is [0.13](https://github.com/societe-generale/code2pg/blob/master/CHANGELOG.md). This brings some changes to the command-line parameters and hopefully clarifies some long standing confusion.
Is it working fine on your end ?

Anthony

**Comment by beaud76** [comment]
Thanks Anthony,
I will try ... soon. And let you know the result.
Philippe.

**Comment by beaud76** [comment]
Thanks Anthony,
I will try ... soon. And let you know the result.
Philippe.

**Comment by beaud76** [comment]
It seems a bug has been introduced in the last commit. I get :
$ ./code2pg --help
Global symbol "%RGEX_SEARCH" requires explicit package name (did you forget to declare "my %RGEX_SEARCH"?) at ./code2pg line 69.
Execution of ./code2pg aborted due to compilation errors.

**Comment by beaud76** [comment]
When the missing E in the %RGEX_SEARCH variable name is added, it works fine.
(At least the analysis of some application code produces an html report, that I now have to closely look at ;-))

**Comment by e7e6** [comment]
Oups ! Now corrected.
