### ISSUE TITLE
Doc: add default value for --leveln-minutes parameters

### ISSUE THREAD

**Issue by beaud76** [societe-generale/code2pg#6]
Great job Anthony !
That would be interesting to add in the documentation the default value of the --level parameters. (1, 4, 8 and 16 minutes respectively, if I read the code correctly).
Best Regards. Philippe.

**Comment by e7e6** [comment]
Hi Philippe,
thanks for raising the issue. It's now corrected in the pod file and in the --help switch.
Best regards,
Anthony
