### ISSUE TITLE
Issues running the script 

### ISSUE THREAD

**Issue by Genesis131** [societe-generale/code2pg#8]
Hello,

First of all thanks for this really nice tool :+1: 

I am having an issue when running the script on my Redhat 6.4.

`# ./code2pg`

`Type of arg 1 to keys must be hash (not hash element) at ./code2pg line 1451, near "} ) "
Execution of ./code2pg aborted due to compilation errors.`

I am working for a big company so I can't access to all of yum's repos.

Perl v5.10.1 is installed. 

I had to manually install by creating their files : 
-http://cpansearch.perl.org/src/LUNATIC/Text-ASCIITable-0.22/lib/Text/ASCIITable.pm
-http://cpansearch.perl.org/src/RCLAMP/File-Find-Rule-0.34/lib/File/Find/Rule.pm
-http://cpansearch.perl.org/src/RCLAMP/Text-Glob-0.11/lib/Text/Glob.pm
-http://cpansearch.perl.org/src/RCLAMP/Number-Compare-0.03/lib/Number/Compare.pm
-http://cpansearch.perl.org/src/VPARSEVAL/List-MoreUtils-0.17/lib/List/MoreUtils.pm

Do you have any idea of what I could do ?

Thanks a lot !

Ps: Please excuse my English it's not my mother tongue :)

**Comment by e7e6** [comment]
Hi @Genesis131, thanks for raising the issue. It presents itself with some specific Perl versions and was hopefully corrected in the rest of the script. Please let me know if the script runs fine now.

**Comment by Genesis131** [comment]
Hi !  

It seems like everything works perfectly fine !

Thanks a lot !

**Comment by e7e6** [comment]
Ok good. I'll close the issue then. 
Having to install those modules is rather cumbersome on RHEL and I will have to see what I can do to make it easier.
